apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
  labels:
    some-label: pod

spec:
   containers:
    - name: docker
      image: docker:19.03
      command:
        - cat
      tty: true
      privileged: true
  
